// flow-typed signature: 5de2980f3cadc4214efaee6f322aabeb
// flow-typed version: <<STUB>>/webpack-reporter-plugin_v^2.0.0/flow_v0.104.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-reporter-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-reporter-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-reporter-plugin/dist/format' {
  declare module.exports: any;
}

declare module 'webpack-reporter-plugin/dist' {
  declare module.exports: any;
}

declare module 'webpack-reporter-plugin/dist/webpack-console-logger' {
  declare module.exports: any;
}

declare module 'webpack-reporter-plugin/dist/webpack-notifier' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-reporter-plugin/dist/format.js' {
  declare module.exports: $Exports<'webpack-reporter-plugin/dist/format'>;
}
declare module 'webpack-reporter-plugin/dist/index' {
  declare module.exports: $Exports<'webpack-reporter-plugin/dist'>;
}
declare module 'webpack-reporter-plugin/dist/index.js' {
  declare module.exports: $Exports<'webpack-reporter-plugin/dist'>;
}
declare module 'webpack-reporter-plugin/dist/webpack-console-logger.js' {
  declare module.exports: $Exports<'webpack-reporter-plugin/dist/webpack-console-logger'>;
}
declare module 'webpack-reporter-plugin/dist/webpack-notifier.js' {
  declare module.exports: $Exports<'webpack-reporter-plugin/dist/webpack-notifier'>;
}
